version: '3.8'

services:
  postgres:
    image: postgres:14.4-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "docker", "-U", "docker"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - STOCK_DB_USER=docker
      - STOCK_DB_PASSWORD=docker
      - STOCK_DB_NAME=stock
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

  stock:
    build: ./stock
    healthcheck:
      test: curl --silent http://localhost:8080/actuator/health | grep {\"status\":\"UP\"} || exit 1
      timeout: 20s
      interval: 10s
      retries: 5
    environment:
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'

  vue-app:
    build: ./vue-app
    volumes:
      - npm-cache:/root/.npm
    depends_on:
      stock:
        condition: service_healthy
    ports:
      - '3000:3000'

volumes:
  npm-cache:
    external: false
