version: '3.8'

services:
  postgres:
    image: 'postgres:14.4-alpine'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - STOCK_DB_USER=docker
      - STOCK_DB_PASSWORD=docker
      - STOCK_DB_NAME=stock
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

  stock:
    build: ./stock-system
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'