version: '3'

services:

  postgres:
    image: 'postgres:latest'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=docker
      - APP_DB_PASSWORD=docker
      - APP_DB_NAME=stock
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'